from bot.keyboards import CLG2026_LABEL_TYPE, MAIN_LABEL_TYPE, PRICE_TAG_LABEL_TYPE, RECEIPT_LABEL_TYPE


DEFAULT_GENERATION_PRICES = {
    MAIN_LABEL_TYPE: 1,
    CLG2026_LABEL_TYPE: 1,
    PRICE_TAG_LABEL_TYPE: 1,
    RECEIPT_LABEL_TYPE: 1,
}


PRICE_LABEL_ORDER = [
    MAIN_LABEL_TYPE,
    CLG2026_LABEL_TYPE,
    PRICE_TAG_LABEL_TYPE,
    RECEIPT_LABEL_TYPE,
]
